# Makefile for MIBs

mibsdir=/usr/share/snmp/mibs
mibs=DVB-FRONTENDCHARACTERISTICS-MIB.my DVB-MGSIGNALCHARACTERISTICS-MIB.my DVB-MGTR101290-MIB.my

all:
	
clear:
	
install:
	cp $(mibs) $(DESTDIR)$(mibsdir)

