/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef MGDCHTABLE_H
#define MGDCHTABLE_H

/* function declarations */
void init_mgDCHTable(void);
void deinit_mgDCHTable(void);
NetsnmpCacheFree cache_free;
NetsnmpCacheLoad cache_load;

/* column number definitions for table mgDCHTable */
       #define COLUMN_MGDCHINPUTNUMBER		1
       #define COLUMN_MGDCHSIGNALSTRENGTH		2
       #define COLUMN_MGDCHSIGNALBER		3
       #define COLUMN_MGDCHSIGNALSNR		4
       #define COLUMN_MGDCHSIGNALUNCORRECTEDBLOCKS		5
       #define COLUMN_MGDCHSIGNALFREQUENCY		6
#endif /* MGDCHTABLE_H */
