/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <libxml/xpath.h>

#include "SNMPHelper.h"
#include "XMLHelper.h"
#include "config.h"

#include "mgEMMTable.h"

static oid mgEMMTable_oid[] = {1, 3, 6, 1, 4, 1, 2696, 3, 3, 1, 1, 5};
netsnmp_table_data_set *table_set;

/** Initializes the mgEMMTable module */
void init_mgEMMTable(void) {

    /* here we initialize all the tables we're planning on supporting */
    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("mgEMMTable");

    netsnmp_mib_handler *cache_handler;

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("mgEMMTable", "adding indexes to table mgEMMTable\n"));
    netsnmp_table_set_add_indexes(table_set,
            ASN_INTEGER, /* index: mgEMMInputNumber */
            ASN_INTEGER, /* index: mgEMMCaPID */
            0);

    DEBUGMSGTL(("mgEMMTable", "adding column types to table mgEMMTable\n"));
    netsnmp_table_set_multi_add_default_row(table_set,
            COLUMN_MGEMMINPUTNUMBER, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGEMMCAPID, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGEMMCASYSTEMID, ASN_INTEGER, 0,
            NULL, 0,
            0);

    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change mgEMMTable_handler to "NULL" */
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change mgTSTable_handler to "NULL" */
    netsnmp_handler_registration *reginfo = netsnmp_create_handler_registration("mgSignalStrengthTable", NULL,
            mgEMMTable_oid,
            OID_LENGTH(mgEMMTable_oid),
            HANDLER_CAN_RWRITE);
    netsnmp_register_table_data_set(reginfo, table_set, NULL);

    DEBUGMSGTL(("mgEMMTable", "Done initalizing mgEMMTable module\n"));

    cache_handler = netsnmp_get_cache_handler(LONGCACHETIMEOUT, /* how long a cache is valid for */
            cache_load, /* a pointer to the cache loading function */
            cache_free, /* a pointer to the cache freeing function */
            mgEMMTable_oid, OID_LENGTH(mgEMMTable_oid)); /* the OID of the registration point */

    netsnmp_inject_handler(reginfo, cache_handler);
}

int cache_load(netsnmp_cache *cache, void *magic) {
    DEBUGMSGTL(("mgEMMTable", "Load Handler\n"));
    xmlDocPtr doc;
    xmlChar *xpath = (xmlChar*) "/dvb/mg/mgSignalCharacteristics/mgSignalCharacteristicsObjects/mgTSStructure/mgEMMTable/mgEMMEntry";
    xmlNodeSetPtr nodeset;
    xmlXPathObjectPtr result;
    xmlNodePtr cur;
    int i;

    netsnmp_table_row *row;

    int mgEMMInputNumber = -1;
    int mgEMMCaPID = -1;
    int mgEMMCASystemID = -1;

    doc = getXMLDoc();
    if (doc == NULL) {
        DEBUGMSGTL(("mgEMMTable", "Problem with loading file %s, keeping old values in table.\n", INPUTXMLDOCUMENTPATH));
        return SNMP_ERR_NOERROR;
    }

    cleanTableSet(table_set);

    result = getNodesPtr(doc, xpath);

    if (result) {
        nodeset = result->nodesetval;
        for (i = 0; i < nodeset->nodeNr; i++) {
            cur = nodeset->nodeTab[i]->xmlChildrenNode;
            while (cur != NULL) {
                if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgEMMInputNumber"))) {
                    mgEMMInputNumber = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgEMMTable", "mgEMMInputNumber: %d\n", mgEMMInputNumber));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgEMMCaPID"))) {
                    mgEMMCaPID = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgEMMTable", " mgEMMCaPID: %d\n", mgEMMCaPID));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgEMMCASystemID"))) {
                    mgEMMCASystemID = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgEMMTable", "mgEMMCASystemID: %d\n", mgEMMCASystemID));
                }
                cur = cur->next;
            }
            row = netsnmp_create_table_data_row();
            netsnmp_table_row_add_index(row, ASN_INTEGER, &mgEMMInputNumber, sizeof (mgEMMInputNumber));
            netsnmp_table_row_add_index(row, ASN_INTEGER, &mgEMMCaPID, sizeof (mgEMMCaPID));
            netsnmp_set_row_column(row, 3, ASN_INTEGER, &mgEMMCASystemID, sizeof (mgEMMCASystemID));
            netsnmp_table_dataset_add_row(table_set, row);

            mgEMMInputNumber = -1;
            mgEMMCaPID = -1;
            mgEMMCASystemID = -1;
        }
    } else {
        DEBUGMSGTL(("mgEMMTable", "Data loaded from file %s is empty.\n", INPUTXMLDOCUMENTPATH));
    }
    closeXML(doc, result);
    return SNMP_ERR_NOERROR;

}

void cache_free(netsnmp_cache *cache, void *magic) {
    DEBUGMSGTL(("mgEMMTable", "Free Handler\n"));
}

void deinit_mgEMMTable(void) {
    netsnmp_delete_table_data_set(table_set);
    table_set = NULL;
    unregister_mib(mgEMMTable_oid, OID_LENGTH(mgEMMTable_oid));
}


