/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef MGEMMTABLE_H
#define MGEMMTABLE_H

/* function declarations */
void init_mgEMMTable(void);
void deinit_mgTSTable(void);
NetsnmpCacheFree cache_free;
NetsnmpCacheLoad cache_load;



/* column number definitions for table mgEMMTable */
       #define COLUMN_MGEMMINPUTNUMBER		1
       #define COLUMN_MGEMMCAPID		2
       #define COLUMN_MGEMMCASYSTEMID		3
#endif /* MGEMMTABLE_H */
