/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef MGNITDELIVERYSYSTEMTABLE_H
#define MGNITDELIVERYSYSTEMTABLE_H

/* function declarations */
void init_mgNITDeliverySystemTable(void);
void deinit_mgNITDeliverySystemTable(void);
NetsnmpCacheFree cache_free;
NetsnmpCacheLoad cache_load;

/* column number definitions for table mgNITDeliverySystemTable */
       #define COLUMN_MGNITDSINPUTNUMBER		1
       #define COLUMN_MGNITDSSYSTEMTYPE		2
       #define COLUMN_MGNITDSFREQUENCY		3
       #define COLUMN_MGNITDSFECOUTER		4
       #define COLUMN_MGNITDSCABLEMODULATION		5
       #define COLUMN_MGNITDSSYMBOLRATE		6
       #define COLUMN_MGNITDSFECINNER		7
       #define COLUMN_MGNITDSORBITALPOSITION		8
       #define COLUMN_MGNITDSWESTEASTFLAG		9
       #define COLUMN_MGNITDSPOLARIZATION		10
       #define COLUMN_MGNITDSSATELLITEMODULATION		11
       #define COLUMN_MGNITDSBANDWIDTH		12
       #define COLUMN_MGNITDSCONSTELLATION		13
       #define COLUMN_MGNITDSHIERARCHYINFORMATION		14
       #define COLUMN_MGNITDSCODERATEHPSTREAM		15
       #define COLUMN_MGNITDSCODERATELPSTREAM		16
       #define COLUMN_MGNITDSGUARDINTERVAL		17
       #define COLUMN_MGNITDSTRANSMISSIONMODE		18
       #define COLUMN_MGNITDSOTHERFREQUENCYFLAG		19
#endif /* MGNITDELIVERYSYSTEMTABLE_H */
