/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <libxml/xpath.h>

#include "SNMPHelper.h"
#include "XMLHelper.h"
#include "config.h"

#include "mgNITDeliverySystemTable.h"

static oid mgNITDeliverySystemTable_oid[] = {1, 3, 6, 1, 4, 1, 2696, 3, 3, 1, 1, 8};
netsnmp_table_data_set *table_set;

/** Initializes the mgNITDeliverySystemTable module */
void
init_mgNITDeliverySystemTable(void) {
    /* here we initialize all the tables we're planning on supporting */
    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("mgNITDeliverySystemTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    netsnmp_mib_handler *cache_handler;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("mgNITDeliverySystemTable", "adding indexes to table mgNITDeliverySystemTable\n"));
    netsnmp_table_set_add_indexes(table_set,
            ASN_INTEGER, /* index: mgNITDSInputNumber */
            0);

    DEBUGMSGTL(("mgNITDeliverySystemTable", "adding column types to table mgNITDeliverySystemTable\n"));
    netsnmp_table_set_multi_add_default_row(table_set,
            COLUMN_MGNITDSINPUTNUMBER, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSSYSTEMTYPE, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSFREQUENCY, ASN_OCTET_STR, 0,
            NULL, 0,
            COLUMN_MGNITDSFECOUTER, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSCABLEMODULATION, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSSYMBOLRATE, ASN_UNSIGNED, 0,
            NULL, 0,
            COLUMN_MGNITDSFECINNER, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSORBITALPOSITION, ASN_OCTET_STR, 0,
            NULL, 0,
            COLUMN_MGNITDSWESTEASTFLAG, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSPOLARIZATION, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSSATELLITEMODULATION, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSBANDWIDTH, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSCONSTELLATION, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSHIERARCHYINFORMATION, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSCODERATEHPSTREAM, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSCODERATELPSTREAM, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSGUARDINTERVAL, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSTRANSMISSIONMODE, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGNITDSOTHERFREQUENCYFLAG, ASN_INTEGER, 0,
            NULL, 0,
            0);

    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change mgNITDeliverySystemTable_handler to "NULL" */
    netsnmp_handler_registration *reginfo = netsnmp_create_handler_registration("mgNITDeliverySystemTable", NULL,
            mgNITDeliverySystemTable_oid,
            OID_LENGTH(mgNITDeliverySystemTable_oid),
            HANDLER_CAN_RWRITE);
    netsnmp_register_table_data_set(reginfo, table_set, NULL);
    DEBUGMSGTL(("mgNITDeliverySystemTable", "Done initalizing mgNITDeliverySystemTable module\n"));
    cache_handler = netsnmp_get_cache_handler(LONGCACHETIMEOUT, /* how long a cache is valid for */
            cache_load, /* a pointer to the cache loading function */
            cache_free, /* a pointer to the cache freeing function */
            mgNITDeliverySystemTable_oid, OID_LENGTH(mgNITDeliverySystemTable_oid)); /* the OID of the registration point */

    netsnmp_inject_handler(reginfo, cache_handler);
}

int cache_load(netsnmp_cache *cache, void *magic) {
    DEBUGMSGTL(("mgNITDeliverySystemTable", "Load Handler\n"));
    xmlDocPtr doc;
    xmlChar *xpath = (xmlChar*) "/dvb/mg/mgSignalCharacteristics/mgSignalCharacteristicsObjects/mgTSStructure/mgNITDeliverySystemTable/mgNITDeliverySystemEntry";
    xmlNodeSetPtr nodeset;
    xmlXPathObjectPtr result;
    xmlNodePtr cur;
    int i;

    netsnmp_table_row *row;

    int mgNITDSInputNumber = -1;
    int mgNITDSSystemType = -1;
    float mgNITDSFrequency = -1;
    int mgNITDSFecOuter = -1;
    int mgNITDSCableModulation = -1;
    int mgNITDSSymbolRate = -1;
    int mgNITDSFecInner = -1;
    float mgNITDSOrbitalPosition = -1;
    int mgNITDSWestEastFlag = -1;
    int mgNITDSPolarization = -1;
    int mgNITDSSatelliteModulation = -1;
    int mgNITDSBandwidth = -1;
    int mgNITDSConstellation = -1;
    int mgNITDSHierarchyInformation = -1;
    int mgNITDSCodeRateHPStream = -1;
    int mgNITDSCodeRateLPStream = -1;
    int mgNITDSGuardInterval = -1;
    int mgNITDSTransmissionMode = -1;
    int mgNITDSOtherFrequencyFlag = -1;

    doc = getXMLDoc();
    if (doc == NULL) {
        DEBUGMSGTL(("mgNITDeliverySystemTable", "Problem with loading file %s, keeping old values in table.\n", INPUTXMLDOCUMENTPATH));
        return SNMP_ERR_NOERROR;
    }

    cleanTableSet(table_set);

    result = getNodesPtr(doc, xpath);

    if (result) {
        nodeset = result->nodesetval;
        for (i = 0; i < nodeset->nodeNr; i++) {
            cur = nodeset->nodeTab[i]->xmlChildrenNode;
            while (cur != NULL) {
                if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSInputNumber"))) {
                    mgNITDSInputNumber = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSInputNumber: %d\n", mgNITDSInputNumber));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSSystemType"))) {
                    mgNITDSSystemType = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", " mgNITDSSystemType: %d\n", mgNITDSSystemType));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSFrequency"))) {
                    mgNITDSFrequency = atof(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSFrequency: %f\n", mgNITDSFrequency));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSFecOuter"))) {
                    mgNITDSFecOuter = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSFecOuter: %d\n", mgNITDSFecOuter));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSCableModulation"))) {
                    mgNITDSCableModulation = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", " mgNITDSCableModulation: %d\n", mgNITDSCableModulation));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSSymbolRate"))) {
                    mgNITDSSymbolRate = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSSymbolRate: %d\n", mgNITDSSymbolRate));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSFecInner"))) {
                    mgNITDSFecInner = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSFecInner: %d\n", mgNITDSFecInner));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSOrbitalPosition"))) {
                    mgNITDSOrbitalPosition = atof(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", " mgNITDSOrbitalPosition: %f\n", mgNITDSOrbitalPosition));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSWestEastFlag"))) {
                    mgNITDSWestEastFlag = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSWestEastFlag: %d\n", mgNITDSWestEastFlag));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSPolarization"))) {
                    mgNITDSPolarization = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSPolarization: %d\n", mgNITDSPolarization));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSSatelliteModulation"))) {
                    mgNITDSSatelliteModulation = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", " mgNITDSSatelliteModulation: %d\n", mgNITDSSatelliteModulation));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSBandwidth"))) {
                    mgNITDSBandwidth = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSBandwidth: %d\n", mgNITDSBandwidth));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSConstellation"))) {
                    mgNITDSConstellation = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSConstellation: %d\n", mgNITDSConstellation));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSHierarchyInformation"))) {
                    mgNITDSHierarchyInformation = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", " mgNITDSHierarchyInformation: %d\n", mgNITDSHierarchyInformation));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSCodeRateHPStream"))) {
                    mgNITDSCodeRateHPStream = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSCodeRateHPStream: %d\n", mgNITDSCodeRateHPStream));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSCodeRateLPStream"))) {
                    mgNITDSCodeRateLPStream = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSCodeRateLPStream: %d\n", mgNITDSCodeRateLPStream));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSGuardInterval"))) {
                    mgNITDSGuardInterval = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", " mgNITDSGuardInterval: %d\n", mgNITDSGuardInterval));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSTransmissionMode"))) {
                    mgNITDSTransmissionMode = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSTransmissionMode: %d\n", mgNITDSTransmissionMode));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgNITDSOtherFrequencyFlag"))) {
                    mgNITDSOtherFrequencyFlag = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgNITDeliverySystemTable", "mgNITDSOtherFrequencyFlag: %d\n", mgNITDSOtherFrequencyFlag));
                }

                cur = cur->next;
            }
            row = netsnmp_create_table_data_row();
            netsnmp_table_row_add_index(row, ASN_INTEGER, &mgNITDSInputNumber, sizeof (mgNITDSInputNumber));
            netsnmp_set_row_column(row, 2, ASN_INTEGER, &mgNITDSSystemType, sizeof (mgNITDSSystemType));
            netsnmp_set_row_column(row, 3, ASN_OCTET_STR, &mgNITDSFrequency, sizeof (mgNITDSFrequency));
            netsnmp_set_row_column(row, 4, ASN_INTEGER, &mgNITDSFecOuter, sizeof (mgNITDSFecOuter));
            netsnmp_set_row_column(row, 5, ASN_INTEGER, &mgNITDSCableModulation, sizeof (mgNITDSCableModulation));
            netsnmp_set_row_column(row, 6, ASN_UNSIGNED, &mgNITDSSymbolRate, sizeof (mgNITDSSymbolRate));
            netsnmp_set_row_column(row, 7, ASN_INTEGER, &mgNITDSFecInner, sizeof (mgNITDSFecInner));
            netsnmp_set_row_column(row, 8, ASN_OCTET_STR, &mgNITDSOrbitalPosition, sizeof (mgNITDSOrbitalPosition));
            netsnmp_set_row_column(row, 9, ASN_INTEGER, &mgNITDSWestEastFlag, sizeof (mgNITDSWestEastFlag));
            netsnmp_set_row_column(row, 10, ASN_INTEGER, &mgNITDSPolarization, sizeof (mgNITDSPolarization));
            netsnmp_set_row_column(row, 11, ASN_INTEGER, &mgNITDSSatelliteModulation, sizeof (mgNITDSSatelliteModulation));
            netsnmp_set_row_column(row, 12, ASN_INTEGER, &mgNITDSBandwidth, sizeof (mgNITDSBandwidth));
            netsnmp_set_row_column(row, 13, ASN_INTEGER, &mgNITDSConstellation, sizeof (mgNITDSConstellation));
            netsnmp_set_row_column(row, 14, ASN_INTEGER, &mgNITDSHierarchyInformation, sizeof (mgNITDSHierarchyInformation));
            netsnmp_set_row_column(row, 15, ASN_INTEGER, &mgNITDSCodeRateHPStream, sizeof (mgNITDSCodeRateHPStream));
            netsnmp_set_row_column(row, 16, ASN_INTEGER, &mgNITDSCodeRateLPStream, sizeof (mgNITDSCodeRateLPStream));
            netsnmp_set_row_column(row, 17, ASN_INTEGER, &mgNITDSGuardInterval, sizeof (mgNITDSGuardInterval));
            netsnmp_set_row_column(row, 18, ASN_INTEGER, &mgNITDSTransmissionMode, sizeof (mgNITDSTransmissionMode));
            netsnmp_set_row_column(row, 19, ASN_INTEGER, &mgNITDSOtherFrequencyFlag, sizeof (mgNITDSOtherFrequencyFlag));

            netsnmp_table_dataset_add_row(table_set, row);

            mgNITDSInputNumber = -1;
            mgNITDSSystemType = -1;
            mgNITDSFrequency = -1;
            mgNITDSFecOuter = -1;
            mgNITDSCableModulation = -1;
            mgNITDSSymbolRate = -1;
            mgNITDSFecInner = -1;
            mgNITDSOrbitalPosition = -1;
            mgNITDSWestEastFlag = -1;
            mgNITDSPolarization = -1;
            mgNITDSSatelliteModulation = -1;
            mgNITDSBandwidth = -1;
            mgNITDSConstellation = -1;
            mgNITDSHierarchyInformation = -1;
            mgNITDSCodeRateHPStream = -1;
            mgNITDSCodeRateLPStream = -1;
            mgNITDSGuardInterval = -1;
            mgNITDSTransmissionMode = -1;
            mgNITDSOtherFrequencyFlag = -1;

        }
    } else {
        DEBUGMSGTL(("mgNITDeliverySystemTable", "Data loaded from file %s is empty.\n", INPUTXMLDOCUMENTPATH));
    }
    closeXML(doc, result);
    return SNMP_ERR_NOERROR;

}

void cache_free(netsnmp_cache *cache, void *magic) {
    DEBUGMSGTL(("mgNITDeliverySystemTable", "Free Handler\n"));
}

void deinit_mgNITDeliverySystemTable(void) {
    netsnmp_delete_table_data_set(table_set);
    table_set = NULL;
    unregister_mib(mgNITDeliverySystemTable_oid, OID_LENGTH(mgNITDeliverySystemTable_oid));
}

