/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef MGPIDTABLE_H
#define MGPIDTABLE_H

/* function declarations */
void init_mgPIDTable(void);
void deinit_init_mgPIDTable(void);
NetsnmpCacheFree cache_free;
NetsnmpCacheLoad cache_load;


/* column number definitions for table mgPIDTable */
       #define COLUMN_MGPIDINPUTNUMBER		1
       #define COLUMN_MGPIDSERVICENUMBER		2
       #define COLUMN_MGPIDNUMBER		3
       #define COLUMN_MGPIDTYPE		4
       #define COLUMN_MGPIDCONDACCESS		5
#endif /* MGPIDTABLE_H */
