/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef MGPIDECMTABLE_H
#define MGPIDECMTABLE_H

/* function declarations */
void init_mgPIDECMTable(void);
void deinit_mgPIDECMTable(void);
NetsnmpCacheFree cache_free;
NetsnmpCacheLoad cache_load;

/* column number definitions for table mgPIDECMTable */
       #define COLUMN_MGPIDECMINPUTNUMBER		1
       #define COLUMN_MGPIDECMSERVICENUMBER		2
       #define COLUMN_MGPIDECMPID		3
       #define COLUMN_MGPIDECMCAPID		4
       #define COLUMN_MGPIDECMCASYSTEMID		5
#endif /* MGPIDECMTABLE_H */
