/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef MGSERVICEECMTABLE_H
#define MGSERVICEECMTABLE_H

/* function declarations */
void init_mgServiceECMTable(void);
void deinit_mgServiceECMTable(void);
NetsnmpCacheFree cache_free;
NetsnmpCacheLoad cache_load;

/* column number definitions for table mgServiceECMTable */
       #define COLUMN_MGSERVICEECMINPUTNUMBER		1
       #define COLUMN_MGSERVICEECMSERVICENUMBER		2
       #define COLUMN_MGSERVICEECMCAPID		3
       #define COLUMN_MGSERVICEECMCASYSTEMID		4
#endif /* MGSERVICEECMTABLE_H */
