/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef MGTSTABLE_H
#define MGTSTABLE_H

/* function declarations */
void init_mgTSTable(void);
void deinit_mgTSTable(void);
NetsnmpCacheFree cache_free;
NetsnmpCacheLoad cache_load;

/* column number definitions for table mgTSTable */
       #define COLUMN_MGTSINPUTNUMBER		1
       #define COLUMN_MGTSID		2
       #define COLUMN_MGTSORIGINALNETWORKID		3
       #define COLUMN_MGTSNETWORKID		4
       #define COLUMN_MGTSNETWORKNAME		5
#endif /* MGTSTABLE_H */