/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 5.0 2002/04/20 07:30:13 hardaker Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <libxml/xpath.h>

#include "SNMPHelper.h"
#include "XMLHelper.h"
#include "config.h"

#include "mgTSTable.h"

/*
 * the variable we want to tie an OID to.  The agent will handle all
 * * GET and SET requests to this variable changing it's value as needed.
 */

netsnmp_table_data_set *table_set;
static oid mgTSTable_oid[] = {1, 3, 6, 1, 4, 1, 2696, 3, 3, 1, 1, 2};

/*
 * our initialization routine, automatically called by the agent 
 * (to get called, the function name must match init_FILENAME()) 
 */
void init_mgTSTable(void) {

    DEBUGMSGTL(("mgTSTable", "Initializing the mgTSId module\n"));
    DEBUGMSGTL(("mgTSTable", "Preparing registration\n"));
    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("mgTSTable");

    netsnmp_mib_handler *cache_handler;

    /* comment this out or delete if you don't support creation of new rows */
    /*table_set->allow_creation = 1;*/

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("mgTSTable", "adding indexes to table mgTSTable\n"));
    netsnmp_table_set_add_indexes(table_set,
            ASN_INTEGER, /* index: mgTSInputNumber */
            0);

    DEBUGMSGTL(("mgTSTable", "adding column types to table mgTSTable\n"));
    netsnmp_table_set_multi_add_default_row(table_set,
            COLUMN_MGTSINPUTNUMBER, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGTSID, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGTSORIGINALNETWORKID, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGTSNETWORKID, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_MGTSNETWORKNAME, ASN_OCTET_STR, 0,
            NULL, 0,
            0);

    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change mgTSTable_handler to "NULL" */
    netsnmp_handler_registration *reginfo = netsnmp_create_handler_registration("mgTSTable", NULL,
            mgTSTable_oid,
            OID_LENGTH(mgTSTable_oid),
            HANDLER_CAN_RWRITE);
    netsnmp_register_table_data_set(reginfo, table_set, NULL);

    DEBUGMSGTL(("mgTSTable", "Done initalizing mgTSTable module\n"));

    cache_handler = netsnmp_get_cache_handler(LONGCACHETIMEOUT, /* how long a cache is valid for */
            cache_load, /* a pointer to the cache loading function */
            cache_free, /* a pointer to the cache freeing function */
            mgTSTable_oid, OID_LENGTH(mgTSTable_oid)); /* the OID of the registration point */

    netsnmp_inject_handler(reginfo, cache_handler);
}

int cache_load(netsnmp_cache *cache, void *magic) {
    DEBUGMSGTL(("mgTSTable", "Load Handler\n"));
    xmlDocPtr doc;
    xmlChar *xpath = (xmlChar*) "/dvb/mg/mgSignalCharacteristics/mgSignalCharacteristicsObjects/mgTSStructure/mgTSTable/mgTSEntry";
    xmlNodeSetPtr nodeset;
    xmlXPathObjectPtr result;
    xmlNodePtr cur;
    int i;

    netsnmp_table_row *row;

    int mgTSInputNumber = -1;
    int mgTSId = -1;
    int mgTSOriginalNetworkID = -1;
    int mgTSNetworkID = -1;
    xmlChar * mgTSNetworkName;
    doc = getXMLDoc();
    if (doc == NULL) {
        DEBUGMSGTL(("mgTSTable", "Problem with loading file %s, keeping old values in table.\n", INPUTXMLDOCUMENTPATH));
        return SNMP_ERR_NOERROR;
    }

    cleanTableSet(table_set);

    result = getNodesPtr(doc, xpath);

    if (result) {
        nodeset = result->nodesetval;
        for (i = 0; i < nodeset->nodeNr; i++) {
            cur = nodeset->nodeTab[i]->xmlChildrenNode;
            while (cur != NULL) {
                if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgTSInputNumber"))) {
                    mgTSInputNumber = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgTSTable", "mgTSInputNumber: %d\n", mgTSInputNumber));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgTSId"))) {
                    mgTSId = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgTSTable", " mgTSId: %d\n", mgTSId));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgTSOriginalNetworkID"))) {
                    mgTSOriginalNetworkID = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgTSTable", "mgTSOriginalNetworkID: %d\n", mgTSOriginalNetworkID));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgTSNetworkID"))) {
                    mgTSNetworkID = atoi(xmlNodeListGetString(doc, cur->xmlChildrenNode, 1));
                    DEBUGMSGTL(("mgTSTable", "mgTSNetworkID: %d\n", mgTSNetworkID));
                } else if ((!xmlStrcmp(cur->name, (const xmlChar *) "mgTSNetworkName"))) {
                    mgTSNetworkName = xmlNodeListGetString(doc, cur->xmlChildrenNode, 1);
                    DEBUGMSGTL(("mgTSTable", "mgTSNetworkName: %s\n", mgTSNetworkName));
                }
                cur = cur->next;
            }
            row = netsnmp_create_table_data_row();
            netsnmp_table_row_add_index(row, ASN_INTEGER, &mgTSInputNumber, sizeof (mgTSInputNumber));
            netsnmp_set_row_column(row, 2, ASN_INTEGER, &mgTSId, sizeof (mgTSId));
            netsnmp_set_row_column(row, 3, ASN_INTEGER, &mgTSOriginalNetworkID, sizeof (mgTSOriginalNetworkID));
            netsnmp_set_row_column(row, 4, ASN_INTEGER, &mgTSNetworkID, sizeof (mgTSNetworkID));
            netsnmp_set_row_column(row, 5, ASN_OCTET_STR, mgTSNetworkName, strlen(mgTSNetworkName));
            netsnmp_table_dataset_add_row(table_set, row);
            
            mgTSInputNumber = -1;
            mgTSId = -1;
            mgTSOriginalNetworkID = -1;
            mgTSNetworkID = -1;
            mgTSNetworkName = 0;
        }
    } else {
        DEBUGMSGTL(("mgTSTable", "Data loaded from file %s is empty.\n", INPUTXMLDOCUMENTPATH));
    }
    closeXML(doc, result);
    return SNMP_ERR_NOERROR;
}

void cache_free(netsnmp_cache *cache, void *magic) {
    DEBUGMSGTL(("mgTSTable", "Free Handler\n"));
}

void deinit_mgTSTable(void) {
    netsnmp_delete_table_data_set(table_set);
    table_set = NULL;
    unregister_mib(mgTSTable_oid, OID_LENGTH(mgTSTable_oid));
}


